### ISSUE TITLE
Color scheme? 

### ISSUE THREAD

**Issue by decryptedchaos** [antoniotejada/Trilium-SyntaxHighlightWidget#16]
This almost perfectly solves the problem..  with one exception that may or may not be a problem for others.. 

Is it possible to (even manually) change the color scheme?  

the colors are not very pleasing particularly the blue on dark backgrounds   I'd prefer pastel colors on dark backgrounds. 

![image](https://github.com/antoniotejada/Trilium-SyntaxHighlightWidget/assets/1302391/4e6fd295-d487-4be6-b79e-17963126cad9)

**Comment by decryptedchaos** [comment]
Nevermind,  I found the stylesheet.  

Here's my modification if anyone wants it.  

Replace the stylesheet between the <style> tags in the CONST at the top of the main script file. 

```css
pre code.hljs {
    display: block;
    overflow-x: auto;
    padding: 1em
}

code.hljs {
    padding: 3px 5px
}

.hljs {
    background: #fff;
    color: #000
}

.hljs-comment,
.hljs-quote,
.hljs-variable {
    color: green
}

.hljs-built_in,
.hljs-keyword,
.hljs-name,
.hljs-selector-tag,
.hljs-tag {
    color: rgb(111, 130, 255)
}

.hljs-addition,
.hljs-attribute,
.hljs-literal,
.hljs-section,
.hljs-string,
.hljs-template-tag,
.hljs-template-variable,
.hljs-title,
.hljs-type {
    color: #a24ba2
}

.hljs-deletion,
.hljs-meta,
.hljs-selector-attr,
.hljs-selector-pseudo {
    color: #5399ae
}

.hljs-doctag {
    color: rgb(220, 232, 140))
}

.hljs-attr {
    color: red
}

.hljs-bullet,
.hljs-link,
.hljs-symbol {
    color: #00b0e8
}

.hljs-emphasis {
    font-style: italic
}

.hljs-strong {
    font-weight: 700
}

```

I like this much better 

![image](https://github.com/antoniotejada/Trilium-SyntaxHighlightWidget/assets/1302391/f4ee48a3-b9c7-4250-9072-dbab7ce88d47)
